title: "Vecvec's blog & suchlike"
name: "Vecvec"

remote_theme: mmistakes/minimal-mistakes@b6fcae623322a4e322a2da328d591e239565ca2b

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single